//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgencyMaster
    {
        public string AID { get; set; }
        public string NameOfAgency { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Phone { get; set; }
        public string RepFirstName { get; set; }
        public string RepLastName { get; set; }
        public string TIN { get; set; }
    }
}
