//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingTable
    {
        public int SID { get; set; }
        public string FiscalYear { get; set; }
        public string NPI { get; set; }
        public string NYCI { get; set; }
        public string StudentLastName { get; set; }
        public string StudentFirstName { get; set; }
        public string Frequency { get; set; }
        public string GroupSize { get; set; }
        public string Duration { get; set; }
        public string Language { get; set; }
        public string ServiceStartDate { get; set; }
        public string ServiceEndDate { get; set; }
        public string FundingCode { get; set; }
    }
}
