//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CurrentTherapists
    {
        public string SID { get; set; }
        public string FundingCode { get; set; }
        public string BoroughCode { get; set; }
        public string SchoolLocationCode { get; set; }
        public string HomeDistrict { get; set; }
        public Nullable<System.DateTime> ServiceStart { get; set; }
        public Nullable<System.DateTime> ServiceEnd { get; set; }
        public string Frequency { get; set; }
        public string GroupSize { get; set; }
        public string Duration { get; set; }
        public string Language { get; set; }
        public Nullable<long> RowNum { get; set; }
        public string NPI { get; set; }
        public string FiscalYear { get; set; }
    }
}
